# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Stock Financials Application
run-name: Generating Stock Financials.(${{ inputs.start_date }} to ${{ inputs.end_date }}) #${{github.run_number}}
on:
  workflow_dispatch: 
    inputs:
      script:
        type: choice
        description: Select script to run
        options:
        - dailyprices
      start_date:
        description: Start Date (dd-mm-yyyy)
        required: true
        type: string
      end_date:
        description: End Date (dd-mm-yyyy)
        required: true
        type: string
  
permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
    - name: Create Dist Directory
      run: mkdir -p dist
    - name: Create Stock Financials Artifact
      run: |
          python Daily_Prices.py ${{inputs.start_date}} ${{inputs.end_date}}
          mv DailyPrices.xlsx dist/DailyPrices_$(date +%d-%m-%Y_%H%M%S).xlsx
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DailyPrices
        path: dist/DailyPrices*.xlsx
